[project]
name = "briefly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-deepseek>=0.1.4",
    "streamlit>=1.49.1",
]
